/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Skripsi_Dicky;


import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Software
 */
public class cuti extends javax.swing.JFrame {

    /**
     * Creates new form master_data_gol
     */
    
   JasperReport jasperReport; 
JasperDesign jasperDesign;
JasperPrint jasperPrint;

Map <String,Object> parham = new HashMap<String,Object>();
Connection conn = new koneksidb.koneksi().getConnection();
    ResultSet r;
    Statement s;
    private Object [][] data_golongan=null;
    private String[] label={"Kode Golongan","Pangkat","Golongan/ Ruang","Gaji Pokok (Rp)"};
    
    public cuti() {
        initComponents();      
          
    }

 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEfect = new pelajaran3.PanelEfect();
        panel_izin = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtabelabsen = new javax.swing.JTable();
        txtAbsen_keterangan = new javax.swing.JTextField();
        btnAbsen_simpan = new javax.swing.JButton();
        radAbsen_cuti = new javax.swing.JRadioButton();
        radAbsen_izin = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        btnAbsen_ubah = new javax.swing.JButton();
        btnAbsen_tambah = new javax.swing.JButton();
        btnAbsen_hapus = new javax.swing.JButton();
        txtAbsen_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtAbsen_nip = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtAbsen_no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_izin.setBackground(new java.awt.Color(0, 51, 204));
        panel_izin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_izin.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 108, -1, -1));

        jtabelabsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "NIP", "Nama", "Jabatan", "Cuti/Izin", "Keterangan", "Foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtabelabsen);

        panel_izin.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 700, 230));

        txtAbsen_keterangan.setBackground(new java.awt.Color(249, 249, 249));
        txtAbsen_keterangan.setEnabled(false);
        panel_izin.add(txtAbsen_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 180, 36));

        btnAbsen_simpan.setText("Simpan");
        panel_izin.add(btnAbsen_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 100, 40));

        radAbsen_cuti.setBackground(new java.awt.Color(204, 204, 204));
        radAbsen_cuti.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        radAbsen_cuti.setText("Cuti");
        radAbsen_cuti.setEnabled(false);
        panel_izin.add(radAbsen_cuti, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        radAbsen_izin.setBackground(new java.awt.Color(204, 204, 204));
        radAbsen_izin.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        radAbsen_izin.setText("Izin");
        radAbsen_izin.setEnabled(false);
        radAbsen_izin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAbsen_izinActionPerformed(evt);
            }
        });
        panel_izin.add(radAbsen_izin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));
        panel_izin.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 108, -1, -1));

        btnAbsen_ubah.setText("Ubah");
        panel_izin.add(btnAbsen_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 70, -1));

        btnAbsen_tambah.setText("Tambah");
        btnAbsen_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsen_tambahActionPerformed(evt);
            }
        });
        panel_izin.add(btnAbsen_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        btnAbsen_hapus.setText("Hapus");
        panel_izin.add(btnAbsen_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 70, -1));

        txtAbsen_tanggal.setBackground(new java.awt.Color(249, 249, 249));
        txtAbsen_tanggal.setToolTipText("");
        txtAbsen_tanggal.setDateFormatString("yyyy-MM-d");
        txtAbsen_tanggal.setEnabled(false);
        panel_izin.add(txtAbsen_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 180, -1));

        jLabel32.setFont(new java.awt.Font("Lucida G", 0, 13)); // NOI18N
        jLabel32.setText("Keterangan :");
        panel_izin.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, 30));

        jLabel33.setFont(new java.awt.Font("Lucida G", 0, 13)); // NOI18N
        jLabel33.setText("NIP :");
        panel_izin.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 30));

        jLabel34.setFont(new java.awt.Font("Lucida G", 0, 13)); // NOI18N
        jLabel34.setText("Tanggal :");
        panel_izin.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        txtAbsen_nip.setBackground(new java.awt.Color(249, 249, 249));
        txtAbsen_nip.setEnabled(false);
        panel_izin.add(txtAbsen_nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 180, 30));

        jLabel35.setFont(new java.awt.Font("Lucida G", 0, 13)); // NOI18N
        jLabel35.setText("Jenis :");
        panel_izin.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        txtAbsen_no.setBackground(new java.awt.Color(249, 249, 249));
        txtAbsen_no.setEnabled(false);
        panel_izin.add(txtAbsen_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 40, 30));

        jLabel6.setText("No_Record");
        panel_izin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 20));

        javax.swing.GroupLayout panelEfectLayout = new javax.swing.GroupLayout(panelEfect);
        panelEfect.setLayout(panelEfectLayout);
        panelEfectLayout.setHorizontalGroup(
            panelEfectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(panelEfectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEfectLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_izin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelEfectLayout.setVerticalGroup(
            panelEfectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(panelEfectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEfectLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_izin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panelEfect, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 740, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radAbsen_izinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAbsen_izinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radAbsen_izinActionPerformed

    private void btnAbsen_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsen_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbsen_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuti().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsen_hapus;
    private javax.swing.JButton btnAbsen_simpan;
    private javax.swing.JButton btnAbsen_tambah;
    private javax.swing.JButton btnAbsen_ubah;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jtabelabsen;
    private pelajaran3.PanelEfect panelEfect;
    private javax.swing.JPanel panel_izin;
    private javax.swing.JRadioButton radAbsen_cuti;
    private javax.swing.JRadioButton radAbsen_izin;
    private javax.swing.JTextField txtAbsen_keterangan;
    private javax.swing.JTextField txtAbsen_nip;
    private javax.swing.JTextField txtAbsen_no;
    private com.toedter.calendar.JDateChooser txtAbsen_tanggal;
    // End of variables declaration//GEN-END:variables
}
